import { Opportunity } from "@/types";

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    title: "Junior Research Fellow (JRF) - THz Detector Materials",
    organization: "ISRO URSC",
    category: "JRF",
    location: "Bangalore",
    stipend: "₹37,000/month",
    deadline: "2026-07-11",
    eligibility: "NET/GATE, MSc Electronics/Physics",
    description:
      "JRF position for characterization of THz detector materials. Ad No. URSC:02:2026, Position Code JRF-E7.",
    apply_link: "https://www.ursc.gov.in",
    tags: ["THz", "detector", "materials", "ISRO", "JRF"],
    is_active: true,
  },
  {
    title: "Junior Research Fellow (JRF) - Thin Film Processes",
    organization: "ISRO URSC",
    category: "JRF",
    location: "Bangalore",
    stipend: "₹37,000/month",
    deadline: "2026-07-11",
    eligibility: "NET/GATE, MSc Electronics/Physics",
    description:
      "JRF position for thin film deposition and process development. Ad No. URSC:02:2026, Position Code JRF-E1.",
    apply_link: "https://www.ursc.gov.in",
    tags: ["thin film", "sputtering", "ISRO", "JRF", "deposition"],
    is_active: true,
  },
  {
    title: "Research Fellow - Spintronics & Magnetic Materials",
    organization: "DRDO SSPL",
    category: "JRF",
    location: "Delhi",
    stipend: "₹37,000/month",
    deadline: "2026-08-15",
    eligibility: "NET/GATE, MSc Physics/Electronics",
    description:
      "Research position in spintronics, magnetic thin films, and magnetization dynamics.",
    apply_link: "https://www.drdo.gov.in",
    tags: ["spintronics", "magnetic", "DRDO", "Delhi", "thin film"],
    is_active: true,
  },
  {
    title: "Project Associate - Thin Film Technology",
    organization: "CSIR-NPL Delhi",
    category: "JRF",
    location: "Delhi",
    stipend: "₹31,000/month",
    deadline: "2026-07-30",
    eligibility: "MSc Electronics/Physics",
    description:
      "Walk-in position for thin film deposition, XRD and VSM characterization.",
    apply_link: "https://www.nplindia.org",
    tags: ["thin film", "XRD", "VSM", "CSIR", "Delhi", "walk-in"],
    is_active: true,
  },
  {
    title: "PhD Position - CoFeB Thin Films & Spintronics",
    organization: "TU Chemnitz",
    category: "PhD",
    location: "Germany",
    stipend: "€1,500/month (DAAD funded)",
    deadline: "2026-09-01",
    eligibility: "MSc Electronics/Physics, Research experience in thin films",
    description:
      "PhD fellowship in spintronics research group, Prof. Georgeta Salvan. DAAD funding available.",
    apply_link: "https://www.tu-chemnitz.de",
    tags: ["PhD", "Germany", "spintronics", "CoFeB", "DAAD", "international"],
    is_active: true,
  },
  {
    title: "SINGA PhD Fellowship - Semiconductor Devices",
    organization: "A*STAR Singapore",
    category: "Fellowship",
    location: "Singapore",
    stipend: "SGD 2,000/month",
    deadline: "2026-08-31",
    eligibility: "MSc/BE Electronics, Strong academic record",
    description:
      "Singapore International Graduate Award for PhD research in semiconductor and materials science.",
    apply_link:
      "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
    tags: ["PhD", "Singapore", "SINGA", "semiconductor", "fellowship", "international"],
    is_active: true,
  },
  {
    title: "Project Scientific Officer - VLSI Design",
    organization: "IIT Delhi IRD",
    category: "JRF",
    location: "Delhi",
    stipend: "₹40,000/month",
    deadline: "2026-07-20",
    eligibility: "BE/MTech VLSI/Electronics",
    description:
      "Project position for VLSI circuit design and verification.",
    apply_link: "http://www.ird.iitd.ac.in",
    tags: ["VLSI", "IIT Delhi", "circuit design", "project"],
    is_active: true,
  },
  {
    title: "Scientist B - Electronics & Radar",
    organization: "DRDO LRDE",
    category: "Govt Job",
    location: "Bangalore",
    stipend: "₹56,100/month (Level 10)",
    deadline: "2026-08-01",
    eligibility: "BE/BTech Electronics, GATE qualified",
    description:
      "Permanent government scientist position in DRDO's radar research establishment.",
    apply_link: "https://www.drdo.gov.in",
    tags: ["DRDO", "Scientist B", "radar", "permanent job", "government"],
    is_active: true,
  },
  {
    title: "MEXT Research Student Fellowship",
    organization: "Japanese Government",
    category: "Fellowship",
    location: "Japan",
    stipend: "¥143,000/month",
    deadline: "2026-05-31",
    eligibility: "MSc completed, Under 35 years",
    description:
      "Japanese government scholarship for research in electronics and semiconductor fields at top Japanese universities.",
    apply_link:
      "https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html",
    tags: ["Japan", "MEXT", "fellowship", "international", "research"],
    is_active: true,
  },
  {
    title: "Embedded Systems Engineer",
    organization: "Texas Instruments India",
    category: "Private Job",
    location: "Bangalore",
    stipend: "₹8-14 LPA",
    deadline: "2026-07-15",
    eligibility: "BE/MTech Electronics, C/C++ skills",
    description:
      "Embedded firmware development for analog and mixed-signal ICs.",
    apply_link: "https://careers.ti.com",
    tags: ["embedded", "firmware", "Texas Instruments", "private", "Bangalore"],
    is_active: true,
  },
];
